apiVersion: v1
kind: Pod
metadata:
  name: app1-pod
  labels:
    app: app1
spec:
  containers:
    - name: app1-container
      image: nginx
      env:
        - name: app1name
          valueFrom:
            configMapKeyRef:
              name: app1-config
              key: app1name
